name: Next.js App CI

on:
  pull_request:
    branches: ["*"]

jobs:
  all-cli-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: yarn install
      - name: Build application
        run: yarn build
      - name: Run linter
        run: yarn lint
      - name: Check types
        run: yarn tsc --noEmit
